version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis_app_net
  app:
    build: .
    image: 2974/garage-api:1.0.0
    ports:
      - "8091:8091"
    depends_on:
      - redis
    networks:
      - redis_app_net
networks:
  redis_app_net:
    driver: bridge