version: '3.8'

services:
  redis:
      image: redis
      ports:
        - "6379:6379"
      networks:
        - garage-network

  springboot:
    image: 2974/garage-api:1.0.0
    container_name: garage-api-container
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8091:8091"
    networks:
      - garage-network
    depends_on:
      - redis

networks:
  garage-network: